app/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('', include('users.urls', namespace='users')),
    path('', include('courses.urls', namespace='courses')),
    path('support/', include('support.urls', namespace='support')),

    path('schema/', get_schema_view(title='API Docs', description='Raven app API'), name='api-schema'),
    path('docs/', include_docs_urls(title='API Docs'), name='docs'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/courses/urls.py
from django.urls import include, path
from rest_framework import routers

from courses import views
from courses.api.views import (CourseListView, CourseViewSet,
                               additional_course_student)

app_name = 'courses'

router = routers.SimpleRouter()
router.register('api/courses', CourseViewSet)

urlpatterns = [
    path('courses/', views.CourseView.as_view(), name='courses'),
    path('courses/<slug:the_slug>/', views.CoursesDetailView.as_view(), name='courses-detail'),
    path('courses/<slug:the_slug>/edit/', views.CourseEditView.as_view(), name='courses-edit'),
    path('courses/<slug:the_slug>/delete/<int:num>/', views.delete_lecture_view, name='lectures-delete'),

    path('courses/<slug:the_slug>/marks/', views.CourseMarksView.as_view(), name='courses-marks'),
    path('courses/<slug:the_slug>/total-marks/', views.TotalCourseMarkView.as_view(), name='courses-total-marks'),
    path('courses/<slug:the_slug>/my-marks/', views.MyCourseMarksView.as_view(), name='my-marks'),
    path('courses/<slug:the_slug>/marks/delete/<int:num>/', views.delete_course_mark, name='courses-marks-delete'),
    path('courses/marks/edit/<int:pk>/', views.CourseMarkEditView.as_view(), name='courses-marks-edit'),

    path('courses/<slug:the_slug>/marks/final/set/<int:pk>/', views.set_final_course_mark_view, name='set-final-mark'),
    path('courses/<slug:the_slug>/marks/final/edit/<int:pk>/', views.edit_final_course_mark_view,
         name='edit-final-mark'),

    path('courses/lecture/<int:pk>/detail/', views.LectureDetailView.as_view(), name='lectures-detail'),
    path('courses/lecture/<int:pk>/edit/', views.LectureEditView.as_view(), name='lectures-edit'),
    path('courses/lecture/<int:pk>/file/add/', views.lecture_add_file, name='lectures-file-add'),
    path('courses/lecture/<int:pk>/file/delete/<int:num>', views.delete_lecture_file, name='lectures-file-delete'),
    path('courses/<slug:the_slug>/lecture/create/', views.LectureCreateView.as_view(), name='lectures-create'),

    path('courses/laboratory/<int:pk>/', views.LaboratoryDetailView.as_view(), name='laboratory-detail'),
    path('courses/laboratory/<int:pk>/edit/', views.LaboratoryEditView.as_view(), name='laboratory-edit'),
    path('courses/<slug:the_slug>/laboratory/create/', views.LaboratoryCreateView.as_view(), name='laboratory-create'),
    path('courses/laboratory/<int:pk>/file/add/', views.laboratory_add_file, name='laboratory-file-add'),
    path('courses/laboratory/<int:pk>/file/delete/<int:num>/', views.delete_laboratory_file,
         name='laboratory-file-delete'),

    path('courses/laboratory/<int:pk>/assignments/add/', views.AssignmentCreateView.as_view(),
         name='assignments-create'),
    path('courses/laboratory/<int:pk>/assignments/delete/<int:num>/', views.delete_assignment_view,
         name='assignments-delete'),


    path('courses/<slug:the_slug>/groups/', views.CourseGroupJoinListView.as_view(), name='group'),
    path('courses/<slug:the_slug>/groups/create/', views.course_group_create_view, name='group-create'),
    path('courses/<slug:the_slug>/groups/join/<int:num>', views.course_group_join_view, name='group-join-group'),
    path('courses/groups/<int:pk>/', views.CourseGroupEditView.as_view(), name='group-edit'),
    path('courses/<slug:the_slug>/groups/<int:num>/delete/', views.course_group_delete_view, name='group-delete'),

    path('courses/<slug:the_slug>/notices/', views.CourseNoticeView.as_view(), name='notices'),

    path('', include(router.urls)),
    path('api/list/courses/', CourseListView.as_view()),
    path('api/courses/<slug:the_slug>/additional-student/', additional_course_student),
]

app/support/urls.py
from django.urls import path

from support import views

app_name = 'support'

urlpatterns = [
    path('contact/', views.TicketCreateView.as_view(), name='support-contact'),
]

app/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('assignments/', views.AssignmentsView.as_view(), name='assignments'),
    path('schedule/', views.ScheduleView.as_view(), name='schedule'),
    path('notices/', views.NoticeView.as_view(), name='notices'),
    path('marks/', views.MarksView.as_view(), name='marks'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('profile/<int:pk>/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile-edit'),
    path('profile/img/delete/', views.delete_profile_image, name='profile-img-delete'),
]

app/users/models.py
import datetime
import os
import uuid

from django.conf import settings
from django.contrib.auth import models as auth_models
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from users import managers


def get_file_path(instance, filename: str) -> str:
    today = datetime.date.today().strftime("%Y-%m-%d")
    return os.path.join(settings.UPLOAD_FILES_DIR, today, str(uuid.uuid4()) + filename)


GENDER_CHOICES = (
    ('male', _('Male')),
    ('female', _('Female')),
    ('none', 'none'),
)

ROLE_CHOICES = (
    ('student', _('Student')),
    ('teacher', _('Teacher')),
)


class User(auth_models.AbstractUser):
    """
    Custom User model for raven platform.

    email: PK                 user's email, used for logging in
    first_name: str           user's first name
    last_name: str            user's last name
    ...

    if role == 'student'
    grade: FK(...)            user's grade/class model
    grades: FK(...)           user's grades

    if role == 'teacher':
    running_courses: FK(...)
    """
    username = None

    first_name = models.CharField(max_length=30, blank=True, verbose_name=_('First name'))
    last_name = models.CharField(max_length=150, blank=True, verbose_name=_('Last name'))

    email = models.EmailField(unique=True, verbose_name=_('Email address'))
    address = models.CharField(max_length=200, blank=True, verbose_name=_('Address'),
                               help_text=_('<b>Address in format</b>: [STREET NAME] [NUMBER], [CITY]'))
    phone = models.CharField(max_length=9, blank=True, verbose_name=_('Phone number'))
    gender = models.CharField(max_length=10, default='none', choices=GENDER_CHOICES,
                              verbose_name=_("User's gender"))
    role = models.CharField(max_length=9, choices=ROLE_CHOICES)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(verbose_name=_('Date joined'), default=timezone.now)
    date_birth = models.DateField(verbose_name=_('Date of birth'), blank=True, null=True,
                                  help_text=_('<b>Birthday date in format:</b> YYYY-MM-DD'))
    is_online = models.BooleanField(default=False)
    description = models.TextField(null=True, blank=True, default="")
    image = models.ImageField(upload_to=get_file_path, default=settings.DEFAULT_USER_IMAGE)
    first_login = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ('first_name', 'last_name',)

    objects = managers.CustomUserManager()

    @property
    def full_username(self) -> str:
        return f"{self.first_name} {self.last_name} ({self.email})"

    @property
    def is_student(self) -> bool:
        return self.role == 'student'

    @property
    def is_teacher(self) -> bool:
        return self.role == 'teacher'

    def __str__(self):
        return self.full_username

    def get_absolute_url(self):
        return reverse('users:profile-detail', args=(self.pk,))

    def get_image_url(self):
        return self.image.url


class Teacher(User):
    """
    Teacher is a submodel of the User
    """
    objects = managers.TeacherUserManager()

    class Meta:
        proxy = True
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")


class Student(User):
    """
    Student is a submodel of the User
    """
    objects = managers.StudentUserManager()

    class Meta:
        proxy = True
        verbose_name = _("Student")
        verbose_name_plural = _("Students")


@receiver(user_logged_in)
def got_online(sender, user, request, **kwargs):
    user.is_online = True
    user.save()


@receiver(user_logged_out)
def got_offline(sender, user, request, **kwargs):
    user.is_online = False
    user.save()

app/templates/dashboard/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block title %}Strona główna{% endblock title %}

{% block content %}
  <div class="w-full h-full bg-gray-100">
    {% include "dashboard/sidebar.html" %}
    <div id = "dashboard_content" class="pt-12 md:ml-4 md:pt-0 md:px-8 lg:px-16 xl:px-32">
      {% block dashboard_content %}
      {% endblock dashboard_content %}
    </div>
  </div>
{% endblock content %}
{% block extrascripts %}{% endblock extrascripts %}
{% block extraheads %}{% endblock extraheads %}

app/templates/dashboard/profile-detail.html
{% extends "dashboard/profile.html" %}
{% load static %}

{% block title %}{{ user.first_name }} {{ user.last_name }}{% endblock title %}


{% block profile_header %}
{% endblock profile_header %}

app/templates/dashboard/profile.html
{% extends "dashboard/dashboard.html" %}
{% load static %}

{% block title %}Mój profil{% endblock title %}

{% block dashboard_content %}
  <div class="font-sans leading-tight bg-grey-lighter p-4 md:pt-8">
    <div class="max-w-full mx-auto bg-white rounded-lg overflow-hidden shadow-lg">
      <div class="bg-cover h-40" style="background-image: url('https://images.unsplash.com/photo-1522093537031-3ee69e6b1746?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a634781c01d2dd529412c2d1e2224ec0&auto=format&fit=crop&w=2098&q=80');"></div>
      <div class="border-b px-4 pb-6">
        <div class="text-center sm:text-left sm:flex mb-1">
          <div class="flex justify-center">
            <img class="h-48 w-48 sm:h-32 sm:w-32 rounded-full border-4 border-white -mt-16 mr-4" src="{{ profile.image.url }}" alt="">
          </div>
          <div class="py-1">
            <div class="font-bold text-2xl mb-1 sm:flex items-center">
              <span>{{ profile.first_name }} {{ profile.last_name }}</span>
              {% if profile.is_online %}
                <span class="ml-2 inline rounded-full bg-green-400 uppercase px-2 py-1 text-xs text-white font-bold">Online</span>
              {% else %}
                <span class="ml-2 inline rounded-full bg-red-400 uppercase px-2 py-1 text-xs text-white font-bold">Offline</span>
              {% endif %}
            </div>
            <div class="block md:flex md:items-center">
              <a href="mailto:{{ profile.email }}" class="text-sm text-blue-400 hover:text-blue-500">{{ profile.email }}</a>
            </div>
            <div class="inline-flex md:flex md:items-center mt-2">
              <div class="text-sm inline-flex font-medium text-gray-600 sm:flex items-center">
                <span><svg class="h-6 w-6 text-grey" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28" width="28" height="28">
                  <path d="M10,1.375c-3.17,0-5.75,2.548-5.75,5.682c0,6.685,5.259,11.276,5.483,11.469c0.152,0.132,0.382,0.132,0.534,0c0.224-0.193,5.481-4.784,5.483-11.469C15.75,3.923,13.171,1.375,10,1.375 M10,17.653c-1.064-1.024-4.929-5.127-4.929-10.596c0-2.68,2.212-4.861,4.929-4.861s4.929,2.181,4.929,4.861C14.927,12.518,11.063,16.627,10,17.653 M10,3.839c-1.815,0-3.286,1.47-3.286,3.286s1.47,3.286,3.286,3.286s3.286-1.47,3.286-3.286S11.815,3.839,10,3.839 M10,9.589c-1.359,0-2.464-1.105-2.464-2.464S8.641,4.661,10,4.661s2.464,1.105,2.464,2.464S11.359,9.589,10,9.589"></path>
                </svg></span>
                {{ profile.address }}
                <span class="ml-2"><svg class="svg-icon" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                  <path d="M12.075,10.812c1.358-0.853,2.242-2.507,2.242-4.037c0-2.181-1.795-4.618-4.198-4.618S5.921,4.594,5.921,6.775c0,1.53,0.884,3.185,2.242,4.037c-3.222,0.865-5.6,3.807-5.6,7.298c0,0.23,0.189,0.42,0.42,0.42h14.273c0.23,0,0.42-0.189,0.42-0.42C17.676,14.619,15.297,11.677,12.075,10.812 M6.761,6.775c0-2.162,1.773-3.778,3.358-3.778s3.359,1.616,3.359,3.778c0,2.162-1.774,3.778-3.359,3.778S6.761,8.937,6.761,6.775 M3.415,17.69c0.218-3.51,3.142-6.297,6.704-6.297c3.562,0,6.486,2.787,6.705,6.297H3.415z"></path>
                </svg></span>
                {% if profile.is_student %}Student{% else %}Nauczyciel akademicki{% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="mt-4">
          {% block profile_header %}
            <a href="{% url 'users:profile-edit' %}" class="text-sm font-bold mt-2 mb-4 px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
              Edytuj mój profil
            </a>
          {% endblock profile_header %}
        </div>
      </div>
      <div class="px-4 py-4 border-b">
        {% block profile_courses %}
          {% if request.user.email == profile.email %}
            <div class="w-full px-4">
            <span class="block text-gray-700 uppercase tracking-wide text-gray-700 text-xs font-bold mb-1">
              <a class="hover:text-gray-900" href="{% url 'courses:courses' %}">Bieżące Kursy</a>
            </span>
              {% if courses %}
                <div class="overflow-x-auto mt-2 mb-4">
                  <table class="table-auto border-collapse w-full mt-1">
                    <thead>
                    <tr class="rounded-t-lg text-sm font-medium text-gray-700 text-left" style="font-size: 0.9674rem">
                      <th class="px-4 py-2">Kurs</th>
                      <th class="px-4 py-2">Rocznik</th>
                      <th class="px-4 py-2">Wykładowca</th>
                      <th class="px-4 py-2">Język</th>
                      <th class="px-4 py-2">ECTS</th>
                    </tr>
                    </thead>
                    <tbody class="text-sm font-normal text-gray-700">
                    {% for course in courses %}
                      <tr class="hover:bg-gray-100 border-b border-gray-200 py-10">
                        <td class="px-4 py-4"><a class="text-blue-400 hover:text-blue-500" href="{% url 'courses:courses-detail' course.slug %}">{{ course.name }}</a></td>
                        <td class="px-4 py-4">{{ course.grade }}</td>
                        <td class="px-4 py-4"><a class="text-blue-400 hover:text-blue-500" href="{% url 'users:profile-detail' course.head_teacher.pk %}">{{ course.head_teacher.first_name }} {{ course.head_teacher.last_name }}</a></td>
                        <td class="px-4 py-4">{{ course.language }}</td>
                        <td class="px-4 py-4">{{ course.ects }}</td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
              {% else %}
                <span class="text-xs mb-4 mt-2">Nie należysz do żadnego kursu.</span>
              {% endif %}
            </div>
          {% endif %}
        {% endblock profile_courses %}
        {% block profile_details %}
        <div class="flex flex-row">
          <div class="flex flex-col w-1/2 my-6 px-5 max-w-full mx-auto">
            <div class="w-full overflow-auto h-56 text-sm mb-3 py-5 px-5 max-w-full mx-auto rounded-lg bg-gray-100 text-gray-800">
              <h5 class="font-bold ">O mnie:</h5>
              <hr class="border-0 my-2 bg-gray-500 text-gray-500 h-px">
              {{ profile.description }}
            </div>
            {% if profile.is_student %}
            <div class="w-full overflow-auto :h-32 text-sm mb-3 py-5 px-5 max-w-full mx-auto rounded-lg bg-gray-100 text-gray-800">
              <h5 class="font-bold ">Roczniki:</h5>
              <hr class="border-0 my-2 bg-gray-500 text-gray-500 h-px">
              {% for grade in grades %}
                <h6>{{ grade }}</h6>
              {% endfor %}
            </div>
            {% endif %}
          </div>
          <div class="flex flex-col w-1/2 my-6 px-5 max-w-full mx-auto">
            <div class="w-full overflow-auto h-56 text-sm mb-3 py-5 px-5 max-w-full mx-auto rounded-lg bg-gray-100 text-gray-800">
              <h5 class="font-bold ">Informacje dodatkowe:</h5>
              <hr class="border-0 my-2 bg-gray-500 text-gray-500 h-px">
              <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-1" for="grid-first-name">
                Ostatnie logowanie
              </label>
              <span class="appearance-none block w-full text-gray-700">
                  {%  if profile.last_login %}
                    {{ profile.last_login|date:"d.m.Y (H:i)" }}
                  {% else %} - {% endif %}
            </span>
              <label class="block mt-2 uppercase tracking-wide text-gray-700 text-xs font-bold mb-1" for="grid-first-name">
                Konto utworzone
              </label>
              <span class="appearance-none block w-full text-gray-700">
                {{ profile.date_joined|date:"d.m.Y (H:i)" }}
            </span>
            </div>
            {% if profile.is_student %}
              <div class="w-full overflow-auto :h-32 text-sm mb-3 py-5 px-5 max-w-full mx-auto rounded-lg bg-gray-100 text-gray-800">
                <span class="block text-gray-700 uppercase tracking-wide text-gray-700 text-xs font-bold mb-1">
                  Raporty
                </span>
                {% if request.user.is_student %}
                  <div class="block ml-2 text-blue-400">
                    <a class="text-sm text-blue-400 hover:text-blue-500" href="{% url 'users:marks' %}">Moje oceny</a>
                  </div>
                  <div class="block ml-2 mt-2 text-blue-400">
                    <a class="text-sm text-blue-400 hover:text-blue-500" href="{% url 'users:summary' %}">Historia studiow</a>
                  </div>
                {% endif %}
              </div>
            {% endif %}
          </div>
        </div>
        {% endblock profile_details %}
        {% block profile_content %}
        {% endblock profile_content %}


{% endblock dashboard_content %}

app/templates/dashboard/sidebar.html
{% load static %}

<div id="header" class="hidden md:block">
  <header class="flex fixed shadow-sm justify-end items-center bg-white w-full py-2 px-4">
    <div class="ml-4 flex items-center md:ml-6">
      <a href="{% url 'support:support-contact' %}" class="p-1 border-2 border-transparent text-gray-400 rounded-full hover:text-gray-600 focus:outline-none focus:text-white focus:bg-gray-700">
        <i class="fas fa-question"></i>
      </a>
      <a href="{% url 'users:profile-edit' %}" class="p-1 border-2 border-transparent text-gray-400 rounded-full hover:text-gray-600 focus:outline-none focus:text-white focus:bg-gray-700">
        <i class="fas fa-cog"></i>
      </a>
      <a href="{% url 'users:notices' %}" class="p-1 border-2 border-transparent text-gray-400 rounded-full hover:text-gray-600 focus:outline-none focus:text-white focus:bg-gray-700">
        <i class="far fa-bell"></i>
      </a>
      <div class="ml-3 relative">
        <div>
          <button @click="openMenu()" id="profile-img" class="max-w-xs flex items-center text-sm rounded-full text-white focus:outline-none focus:bg-gray-700 focus:shadow-solid" id="user-menu" aria-label="User menu" aria-haspopup="true">
            <img class="h-8 w-8 rounded-full" src="{{ request.user.image.url }}" alt="">
          </button>
        </div>
        <div id="profile-info" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg hidden" v-bind:class="getClass">
          <div class="py-1 rounded-md bg-white shadow-xs" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
            <a href="{% url 'users:profile' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Mój profil</a>
            <a href="{% url 'users:profile-edit' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Edytuj profil</a>
            <a href="{% url 'users:logout' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Wyloguj</a>
          </div>
        </div>
      </div>
    </div>
  </header>
</div>
<div id="main">
  <button id="openbtn"
          class="openbtn"
          @click="isHidden = !isHidden"
          :style="{marginLeft: isHidden ? '15px' : '300px'}"
  >☰</button>
  <transition name="list">
    <div v-if="!isHidden" id="mySidebar" class="sidebar bg-white shadow-md">
      <div>
        <a href="{% url "users:dashboard" %}" class="{% if request.path == '/' %}bg-gray-200{% endif %} hover:bg-gray-200 ml-4 mr-2 rounded-lg">
          <span>
            <i class="fas fa-home"></i>
          </span>
          <span>Strona Główna</span>
        </a>
        <a href="{% url 'users:schedule' %}" class="{% if '/schedule/' in request.path %}bg-gray-200{% endif %} hover:bg-gray-200 ml-4 mr-2 rounded-lg">
        <span>
          <i class="fas fa-calendar-minus"></i>
        </span>
          <span>Plan zajęć</span>
        </a>
        <a href="{% url "courses:courses" %}" class="{% if '/courses/' in request.path %}bg-gray-200{% endif %} hover:bg-gray-200 ml-4 mr-2 rounded-lg">
        <span>
          <i class="fas fa-home"></i>
        </span>
          <span>Kursy</span>
        </a>
        <a href="{% url 'users:notices' %}" class="{% if '/notices/' in request.path %}bg-gray-200{% endif %} hover:bg-gray-200 ml-4 mr-2 rounded-lg">
          <span>
            <i class="fas fa-calendar"></i>
          </span>
          <span>Ogłoszenia</span>
        </a>
        {% if request.user.is_student %}
          <a href="{% url 'users:assignments' %}" class="{% if '/assignments/' in request.path %}bg-gray-200{% endif %} hover:bg-gray-200 ml-4 mr-2 rounded-lg">
          <span>
            <i class="fas fa-pencil-ruler"></i>
          </span>
            <span>Zadania</span>
          </a>
        <a href="{% url 'users:marks' %}" class="{% if '/marks/' in request.path %}bg-gray-200{% endif %} hover:bg-gray-200 ml-4 mr-2 rounded-lg">
        <span>
          <i class="fas fa-graduation-cap"></i>
        </span>
          <span>Oceny</span>
        </a>
        {% endif %}
        <div class="hover:bg-gray-200 ml-4 mr-2 rounded-lg">
          <button @click="isHidden3 = !isHidden3" class="dropdown-btn">
            <span><i class="fas fa-user-circle"></i></span>
            <span>Moje konto</span>
            <span><i class="fa fa-caret-down"></i></span>
          </button>
          <div v-if="!isHidden3">
            <a href="{% url 'users:profile' %}">Mój profil</a>
            <a href="{% url 'users:logout' %}">Wyloguj</a>
          </div>
        </div>
      </div>
    </div>
  </transition>
</div>

<script type="application/javascript">
  var app = new Vue({
    delimiters: ['[[', ']]'],
    el: '#header',
    data: {
      isMenuOpen: false,
    },
    computed: {
      getClass: function() {
        return this.isMenuOpen ? 'showMenu' : '';
      },
    },
    methods: {
      openMenu() {
        this.isMenuOpen = !this.isMenuOpen;
      },
    }
  });
</script>
<script type="application/javascript">
  var sidebar= new Vue({
    el: '#main',
    delimiters: ['[[', ']]'],
    data () {
      return {
        isHidden: true,
        isHidden2: true,
        isHidden3: true,
      }
    },
  });
</script>
<style>
  .showMenu {
    display: block;
  }
  *:focus {
    outline: none;
  }
  #mySidebar{
    height: 100%;
    width: 300px;
    position: fixed;
    z-index: 0;
    top: 0;
    left: 0;
    padding-top: 60px;
    white-space: nowrap;
  }

  .openbtn {
    z-index: 0;
    position: relative;
    margin-top: 50px;
    border-radius: .5em;
    font-size: 20px;
    cursor: pointer;
    background-color: #60a5fa;
    color: white;
    padding: 10px 15px;
    border: none;
    transition: 0.3s;
  }
  .sidebar a:hover, .dropdown-btn:hover {
    color: #5a5a5a;
  }
  .openbtn:hover {
    background-color: #444;
  }

  #main {
    padding: 16px;
    width: fit-content;
  }
  .sidebar a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 14px;
    color: #111;
    display: block;
    white-space: nowrap;
    overflow-x: hidden;
  }
  .dropdown-btn {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 14px;
    color: #111;
    white-space: nowrap;
    overflow-x: hidden;
  }
  @media screen and (max-height: 450px) {
    .sidebar {padding-top: 10px;}
    .sidebar a, .dropdown-btn {font-size: 12px;}
  }
  #logo_background{
    width: 145px;
    height: 70px;
    overflow: hidden;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .list-enter,
  .list-leave-to {
    visibility: hidden;
    height: 0;
    margin: 0;
    padding: 0;
    opacity: 0;
  }

  .list-enter-active,
  .list-leave-active {
    transition: opacity .5s;
  }
</style>