app/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('', include('users.urls', namespace='users')),
    path('', include('courses.urls', namespace='courses')),
    path('support/', include('support.urls', namespace='support')),

    path('schema/', get_schema_view(title='API Docs', description='Raven app API'), name='api-schema'),
    path('docs/', include_docs_urls(title='API Docs'), name='docs'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/courses/urls.py
from django.urls import include, path
from rest_framework import routers

from courses import views
from courses.api.views import (CourseListView, CourseViewSet,
                               additional_course_student)

app_name = 'courses'

router = routers.SimpleRouter()
router.register('api/courses', CourseViewSet)

urlpatterns = [
    path('courses/', views.CourseView.as_view(), name='courses'),
    path('courses/<slug:the_slug>/', views.CoursesDetailView.as_view(), name='courses-detail'),
    path('courses/<slug:the_slug>/edit/', views.CourseEditView.as_view(), name='courses-edit'),
    path('courses/<slug:the_slug>/delete/<int:num>/', views.delete_lecture_view, name='lectures-delete'),

    path('courses/<slug:the_slug>/marks/', views.CourseMarksView.as_view(), name='courses-marks'),
    path('courses/<slug:the_slug>/total-marks/', views.TotalCourseMarkView.as_view(), name='courses-total-marks'),
    path('courses/<slug:the_slug>/my-marks/', views.MyCourseMarksView.as_view(), name='my-marks'),
    path('courses/<slug:the_slug>/marks/delete/<int:num>/', views.delete_course_mark, name='courses-marks-delete'),
    path('courses/marks/edit/<int:pk>/', views.CourseMarkEditView.as_view(), name='courses-marks-edit'),

    path('courses/<slug:the_slug>/marks/final/set/<int:pk>/', views.set_final_course_mark_view, name='set-final-mark'),
    path('courses/<slug:the_slug>/marks/final/edit/<int:pk>/', views.edit_final_course_mark_view,
         name='edit-final-mark'),

    path('courses/lecture/<int:pk>/detail/', views.LectureDetailView.as_view(), name='lectures-detail'),
    path('courses/lecture/<int:pk>/edit/', views.LectureEditView.as_view(), name='lectures-edit'),
    path('courses/lecture/<int:pk>/file/add/', views.lecture_add_file, name='lectures-file-add'),
    path('courses/lecture/<int:pk>/file/delete/<int:num>', views.delete_lecture_file, name='lectures-file-delete'),
    path('courses/<slug:the_slug>/lecture/create/', views.LectureCreateView.as_view(), name='lectures-create'),

    path('courses/laboratory/<int:pk>/', views.LaboratoryDetailView.as_view(), name='laboratory-detail'),
    path('courses/laboratory/<int:pk>/edit/', views.LaboratoryEditView.as_view(), name='laboratory-edit'),
    path('courses/<slug:the_slug>/laboratory/create/', views.LaboratoryCreateView.as_view(), name='laboratory-create'),
    path('courses/laboratory/<int:pk>/file/add/', views.laboratory_add_file, name='laboratory-file-add'),
    path('courses/laboratory/<int:pk>/file/delete/<int:num>/', views.delete_laboratory_file,
         name='laboratory-file-delete'),

    path('courses/laboratory/<int:pk>/assignments/add/', views.AssignmentCreateView.as_view(),
         name='assignments-create'),
    path('courses/laboratory/<int:pk>/assignments/delete/<int:num>/', views.delete_assignment_view,
         name='assignments-delete'),


    path('courses/<slug:the_slug>/groups/', views.CourseGroupJoinListView.as_view(), name='group'),
    path('courses/<slug:the_slug>/groups/create/', views.course_group_create_view, name='group-create'),
    path('courses/<slug:the_slug>/groups/join/<int:num>', views.course_group_join_view, name='group-join-group'),
    path('courses/groups/<int:pk>/', views.CourseGroupEditView.as_view(), name='group-edit'),
    path('courses/<slug:the_slug>/groups/<int:num>/delete/', views.course_group_delete_view, name='group-delete'),

    path('courses/<slug:the_slug>/notices/', views.CourseNoticeView.as_view(), name='notices'),

    path('', include(router.urls)),
    path('api/list/courses/', CourseListView.as_view()),
    path('api/courses/<slug:the_slug>/additional-student/', additional_course_student),
]

app/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('assignments/', views.AssignmentsView.as_view(), name='assignments'),
    path('schedule/', views.ScheduleView.as_view(), name='schedule'),
    path('notices/', views.NoticeView.as_view(), name='notices'),
    path('marks/', views.MarksView.as_view(), name='marks'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('profile/<int:pk>/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile-edit'),
    path('profile/img/delete/', views.delete_profile_image, name='profile-img-delete'),
]

app/courses/forms.py
from django import forms

from courses import models

tailwind_form = 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4' \
                 ' mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500'


class LectureCreateForm(forms.Form):
    """
    LectureCreateForm is used to create new Lecture at `courses.views.LectureCreateView`.
    """
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': tailwind_form,
        'placeholder': 'Tytuł',
    }))
    date = forms.DateField(widget=forms.DateInput(attrs={
        'class': tailwind_form,
        'placeholder': '01.01.2021'
    }))
    time = forms.TimeField(widget=forms.TimeInput(attrs={
        'class': tailwind_form,
        'placeholder': '12:30'
    }))
    duration = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': tailwind_form,
        'placeholder': '90',
        'min': '1'
    }))
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'class': tailwind_form,
        'cols': 30,
        'rows': 5
    }))
    show = forms.BooleanField(required=False)
    meeting = forms.BooleanField(initial=True, required=False)


class LaboratoryCreateForm(LectureCreateForm):
    """
    LaboratoryCreateForm is used to create new Laboratory at `courses.views.LaboratoryCreateView`.
    """
    group = forms.ModelChoiceField(queryset=models.CourseGroup.objects.all(),
                                   widget=forms.RadioSelect(attrs={'class': 'text-sm text-gray-700'}))


class CourseFileForm(forms.Form):
    """
    CourseFileForm is used to create/edit file within `course` module.
    """
    filename = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': tailwind_form,
        'placeholder': 'Nazwa pliku',
    }))
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'class': tailwind_form,
        'cols': 30,
        'rows': 5
    }))
    file = forms.FileField(required=True, widget=forms.FileInput(attrs={
        'class': tailwind_form
    }))


class CourseGroupModelForm(forms.ModelForm):
    """
    CourseGroupModelForm is used to create/edit `courses.CourseGroup` objects
    """
    class Meta:
        model = models.CourseGroup
        fields = ('name', 'students',)
        widgets = {
            'name': forms.TextInput(attrs={'class': tailwind_form}),
            'students': forms.CheckboxSelectMultiple(attrs={'class': 'text-sm text-gray-700'})
        }


class CourseNoticeModelForm(forms.ModelForm):
    """
    CourseNoticeModelForm is used to create/edit `courses.CourseNotice` objects
    """
    class Meta:
        model = models.CourseNotice
        fields = ('title', 'content',)
        widgets = {
            'title': forms.TextInput(attrs={'class': tailwind_form}),
            'content': forms.Textarea(attrs={
                'class': tailwind_form,
                'cols': 30,
                'rows': 5
            })
        }


class CourseMarkModelForm(forms.ModelForm):
    """
    CourseMarkModelForm is used to create/edit `courses.CourseMark` objects
    """
    class Meta:
        model = models.CourseMark
        fields = ('mark', 'description')
        widgets = {
            'mark': forms.NumberInput(attrs={'class': tailwind_form}),
            'description': forms.Textarea(attrs={
                'class': tailwind_form,
                'cols': 30,
                'rows': 5,
                'placeholder': 'Opis'
            }),
        }


class CourseSetFinalMarkModelForm(forms.ModelForm):
    """
    CourseSetFinalMarkModelForm is used to create/edit `courses.FinalCourseMark` objects
    """
    class Meta:
        model = models.FinalCourseMark
        fields = ('mark', 'description')
        widgets = {
            'mark': forms.NumberInput(attrs={'class': tailwind_form}),
            'description': forms.Textarea(attrs={
                'class': tailwind_form,
                'cols': 30,
                'rows': 5,
                'placeholder': 'Opis'
            }),
        }


class AssignmentCreateModelForm(forms.ModelForm):
    """
    AssignmentCreateModelForm is used to create/edit `courses.Assignment` objects
    """
    class Meta:
        model = models.Assignment
        fields = ('deadline', 'title', 'content')
        widgets = {
            'deadline': forms.DateTimeInput(attrs={
                'class': tailwind_form,
                'placeholder': '01.01.2021'
            }),
            'title': forms.TextInput(attrs={'class': tailwind_form, 'placeholder': 'Tytul'}),
            'content': forms.Textarea(attrs={
                'class': tailwind_form,
                'cols': 30,
                'rows': 5
            })
        }

app/courses/api/views.py
from rest_framework import generics, mixins, viewsets
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from courses import models
from users import models as users_models

from .permissions import IsTeacherOrReadOnly
from .serializers import CourseAdditionalStudentsSerializer, CourseSerializer


class CourseListView(mixins.ListModelMixin, generics.GenericAPIView):
    queryset = models.Course.objects.all()
    serializer_class = CourseSerializer
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def get_queryset(self):
        user = self.request.user
        qs = models.Course.objects.all()
        if user.is_teacher:
            teacher = users_models.Teacher.objects.get(pk=user.pk)
            qs = qs.filter(teachers__in=[teacher.pk])
        if user.is_student:
            student = users_models.Student.objects.get(pk=user.pk)
            qs = qs.filter(grade__students__in=[student.pk])

        name = self.request.query_params.get('name')
        teacher = self.request.query_params.get('teacher')
        has_exam = int(self.request.query_params.get('exam', 0))
        language = self.request.query_params.get('language')
        actual = self.request.query_params.get('actual')

        if name:
            qs = qs.filter(name__icontains=name)
        if teacher:
            qs = qs.filter(teachers__last_name__icontains=teacher)
        if has_exam and has_exam > 0:
            if has_exam == 1:
                qs = qs.filter(has_exam=True)
            if has_exam == 2:
                qs = qs.filter(has_exam=False)
        if language:
            qs = qs.filter(language=language.upper())
        if actual and actual == 'true':
            qs = [q for q in qs if q.is_actual]
        return qs


class CourseViewSet(mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    queryset = models.Course.objects.all()
    serializer_class = CourseAdditionalStudentsSerializer
    permission_classes = [IsTeacherOrReadOnly, IsAuthenticated]
    lookup_field = "slug"

    def get_queryset(self):
        user = self.request.user
        teacher = users_models.Teacher.objects.get(pk=user.pk)
        return teacher.courses_teaching.all()


@api_view(['POST'])
def additional_course_student(request, the_slug):
    if not request.user.is_authenticated or request.user.role != 'teacher':
        return Response(status=401)
    if request.method == 'POST':
        email = request.data.get('email')
        course = models.Course.objects.get(slug=the_slug)
        if email and course:
            try:
                student = users_models.Student.objects.get(email=email)
                if student in course.grade.students.all() or student in course.additional_students.all():
                    return Response(status=200, data={'message': 'Ten użytkownik jest już dodany.'})
                if student:
                    course.additional_students.add(student)
            except Exception:
                return Response(status=404)
            return Response(status=200, data={'message': 'Pomyślnie dodano uzytkownika do kursu.'})
        return Response(status=400)
    return Response(status=401)

app/templates/courses/marks/edit-final-mark.html
{% extends "dashboard/dashboard.html" %}
{% load static %}

{% block title %}Edytuj ocenę końcową{% endblock title %}


{% block dashboard_content %}
  <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
  <div id="marks" class="font-sans leading-tight bg-grey-lighter p-4 md:pt-8">
    <div class="max-w-full mx-auto bg-white rounded-lg overflow-hidden shadow-lg">
      <div class="px-4 py-4 mx-2">
        <h4 class="text-lg leading-6 font-medium text-gray-900 mb-2">
          <a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses' %}">Kursy</a>
          / <a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses-detail' course.slug %}">{{ course.name }}</a> /
          <a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses-total-marks' course.slug %}">Wykaz ocen</a> /
          Edytuj ocenę końcową
          <form action="" method="POST">
            {% csrf_token %}
            <div class="flex flex-wrap -mx-3 mb-6">
              <div class="w-full sm:w-2/3 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
                  Ocena
                </label>
                {{ form.mark }}
              </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6">
              <div class="w-full sm:w-2/3 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
                  Opis
                </label>
                {{ form.description }}
              </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6 px-3">
              <button type="submit" class="text-sm font-bold mt-2 mb-4 px-3 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
                Aktualizuj
              </button>
              <a href="{% url 'courses:courses-detail' course.slug %}" class="ml-2 text-sm font-bold mt-2 mb-4 px-3 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
                Powrót do kursu
              </a>
            </div>
          </form>
      </div>
    </div>
  </div>
{% endblock dashboard_content %}

app/templates/courses/marks/partial-marks.html
{% extends "dashboard/dashboard.html" %}
{% load static %}

{% block title %}Oceny cząstkowe{% endblock title %}

{% block dashboard_content %}
  <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
  <div id="marks" class="font-sans leading-tight bg-grey-lighter p-4 md:pt-8">
    <div class="max-w-full mx-auto bg-white rounded-lg overflow-hidden shadow-lg">
      <div class="px-4 py-4 mx-2">
        <h4 class="text-lg leading-6 font-medium text-gray-900 mb-2">
          <a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses' %}">Kursy</a>
          / <a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses-detail' course.slug %}">{{ course.name }}</a> /
          <a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses-total-marks' course.slug %}">Wykaz ocen</a> /
          Oceny
        </h4>
        <div class="mb-4 border-b">
          <form action="" method="GET">
            <div class="mb-2 w-full sm:w-1/2 md:w-1/2">
              <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
                FILTRUJ WYSTAWIONE OCENY
              </label>
              <input name="student" placeholder="Imię i nazwisko studenta" type="text" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" value="{{ student }}">
              <button type="submit" class="mt-2 text-sm font-bold mb-4 px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
                Filtruj
              </button>
              <a href="{% url 'courses:courses-marks' course.slug %}" class="mt-2 ml-2 text-sm font-bold mb-4 px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
                Resetuj
              </a>
            </div>
          </form>
        </div>
        {% if marks.all %}
        <div class="overflow-x-auto mt-6">
          <table class="table-auto border-collapse w-full mt-1">
            <thead>
            <tr class="rounded-t-lg text-sm font-medium text-gray-700 text-left" style="font-size: 0.9674rem">
              <th class="px-4 py-2">Student</th>
              <th class="px-4 py-2">Ocena</th>
              <th class="px-4 py-2">Opis</th>
              <th class="px-4 py-2">Prowadzący</th>
              <th class="px-4 py-2">Data</th>
              <th class="px-4 py-2">Edycja</th>
            </tr>
            </thead>
            <tbody class="text-sm font-normal text-gray-700">
            {% for mark in marks %}
              <tr class="hover:bg-gray-100 border-b border-gray-200 py-10">
                <td class="px-4 py-4"><a class="text-blue-400 hover:text-blue-500" href="{% url 'users:profile-detail' mark.student.pk %}">{{ mark.student.first_name }} {{ mark.student.last_name }}</a></td>
                <td class="px-4 py-4">{{ mark.mark }}% ({{ mark.mark_decimal }})</td>
                <td class="px-4 py-4">{% if mark.description %}{{ mark.description }}{% else %}-{% endif %}</td>
                <td class="px-4 py-4"><a class="text-blue-400 hover:text-blue-500" href="{% url 'users:profile-detail' mark.teacher.pk %}">{{ mark.teacher.first_name }} {{ mark.teacher.last_name }}</a></td>
                <td class="px-4 py-4">{{ mark.date }}</td>
                <td class="px-4 py-4"><a href="{% url 'courses:courses-marks-edit' mark.pk %}" class="text-blue-400 hover:text-blue-500">Edytuj</a> / <span @click="deleteMark({{ forloop.counter0 }})" class="cursor-pointer text-red-400 hover:text-red-600">Usuń</span></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        {% else %}
          Brak wystawionych ocen.
        {% endif %}
        <div class="py-4">
          <form action="" method="POST">
            {% csrf_token %}
            <div class="flex flex-wrap -mx-3 mb-6">
              <div class="w-full sm:w-1/3 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
                  Ocena
                </label>
                {{ form.mark }}
              </div>
              <div class="w-full sm:w-1/3 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
                  Email studenta
                </label>
                <input type="email" name="email" placeholder="Adres email studenta" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-last-name">
              </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6">
              <div class="w-full sm:w-2/3 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
                  Opis
                </label>
                {{ form.description }}
              </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6 px-3">
              <button type="submit" class="text-sm font-bold mt-2 mb-4 px-3 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
                Dodaj ocenę
              </button>
              <a href="{% url 'courses:courses-detail' course.slug %}" class="ml-2 text-sm font-bold mt-2 mb-4 px-3 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
                Powrót do kursu
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock dashboard_content %}

{% block extraheads %}
  {{ block.super }}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
{% endblock extraheads %}

{% block extravue %}
  <script type="text/javascript">
    var app = new Vue({
      delimiters: ['[[', ']]'],
      el: '#marks',
      data: {},
      methods: {
        deleteMark: function(num) {
          Swal.fire({
            text: "Czy na pewno chcesz usunąć tę ocenę?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Tak, usuń!',
          }).then((result) => {
            if (result.isConfirmed) {
              const slug = "{{ course.slug }}"
              window.location.href = `/courses/${slug}/marks/delete/${num}/`
            }
          })
        },
      }
    });
  </script>
{% endblock extravue %}

app/templates/courses/marks/total-marks.html
{% extends "dashboard/dashboard.html" %}
{% load static %}

{% block title %}Oceny{% endblock title %}

{% block dashboard_content %}
  <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
  <div id="marks" class="font-sans leading-tight bg-grey-lighter p-4 md:pt-8">
    <div class="max-w-full mx-auto bg-white rounded-lg overflow-hidden shadow-lg">
      <div class="px-4 py-4 mx-2">
        <h4 class="text-lg leading-6 font-medium text-gray-900 mb-2">
          <a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses' %}">Kursy</a>
          / <a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses-detail' course.slug %}">{{ course.name }}</a> /
          Wykaz ocen
        </h4>
        <div class="mb-4 border-b">
          <form action="" method="GET">
            <div class="mb-2 w-full sm:w-1/2 md:w-1/2">
              <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
                FILTRUJ WYSTAWIONE OCENY
              </label>
              <input value="{{ student }}" name="student" placeholder="Imię i nazwisko studenta" type="text" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
              <button type="submit" class="mt-2 text-sm font-bold mb-4 px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
                Filtruj
              </button>
              <a href="{% url 'courses:courses-total-marks' course.slug %}" class="mt-2 ml-2 text-sm font-bold mb-4 px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
                Resetuj
              </a>
            </div>
          </form>
        </div>
        {% if students %}
          <div class="overflow-x-auto mt-6">
            <table class="table-auto border-collapse w-full mt-1">
              <thead>
              <tr class="rounded-t-lg text-sm font-medium text-gray-700 text-left" style="font-size: 0.9674rem">
                <th class="px-4 py-2">Student</th>
                <th class="px-4 py-2">Oceny cząstkowe</th>
                <th class="px-4 py-2">Ocena końcowa</th>
              </tr>
              </thead>
              <tbody class="text-sm font-normal text-gray-700">
              {% for student in students %}
                <tr class="hover:bg-gray-100 border-b border-gray-200 py-10">
                  <td class="px-4 py-4"><a class="text-blue-400 hover:text-blue-500" href="{% url 'users:profile-detail' student.pk %}">{{ student.first_name }} {{ student.last_name }}</a></td>
                  <td class="px-4 py-4">{% if not student.courses_marks.all %}<a class="text-blue-400 hover:text-blue-500" href="{% url 'courses:courses-marks' course.slug %}?student={{ student.first_name }}+{{ student.last_name }}">Edytuj</a>{% else %}{% for mark in student.courses_marks.all %}{% if mark.course == course %}{{ mark.mark }}%{% if not forloop.last %}, {% endif %}{% endif %}{% endfor %}<a class="text-blue-400 hover:text-blue-500 ml-2" href="{% url 'courses:courses-marks' course.slug %}?student={{ student.first_name }}+{{ student.last_name }}">Edytuj</a>{% endif %} </td>
                  <td class="px-4 py-4">{% if student in course.students_with_final_mark %}{{ student.courses_final_marks.first.mark_decimal }}<a class="ml-2 text-blue-400 hover:text-blue-500" href="{% url 'courses:edit-final-mark' course.slug student.pk %}">Edytuj</a>{% else %}<a class="text-blue-400 hover:text-blue-500" href="{% url 'courses:set-final-mark' course.slug student.pk %}">Wstaw</a>{% endif %}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          Brak wystawionych ocen.
        {% endif %}
      </div>
    </div>
  </div>
{% endblock dashboard_content %}