app/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('', include('users.urls', namespace='users')),
    path('', include('courses.urls', namespace='courses')),
    path('support/', include('support.urls', namespace='support')),

    path('schema/', get_schema_view(title='API Docs', description='Raven app API'), name='api-schema'),
    path('docs/', include_docs_urls(title='API Docs'), name='docs'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/courses/urls.py
from django.urls import include, path
from rest_framework import routers

from courses import views
from courses.api.views import (CourseListView, CourseViewSet,
                               additional_course_student)

app_name = 'courses'

router = routers.SimpleRouter()
router.register('api/courses', CourseViewSet)

urlpatterns = [
    path('courses/', views.CourseView.as_view(), name='courses'),
    path('courses/<slug:the_slug>/', views.CoursesDetailView.as_view(), name='courses-detail'),
    path('courses/<slug:the_slug>/edit/', views.CourseEditView.as_view(), name='courses-edit'),
    path('courses/<slug:the_slug>/delete/<int:num>/', views.delete_lecture_view, name='lectures-delete'),

    path('courses/<slug:the_slug>/marks/', views.CourseMarksView.as_view(), name='courses-marks'),
    path('courses/<slug:the_slug>/total-marks/', views.TotalCourseMarkView.as_view(), name='courses-total-marks'),
    path('courses/<slug:the_slug>/my-marks/', views.MyCourseMarksView.as_view(), name='my-marks'),
    path('courses/<slug:the_slug>/marks/delete/<int:num>/', views.delete_course_mark, name='courses-marks-delete'),
    path('courses/marks/edit/<int:pk>/', views.CourseMarkEditView.as_view(), name='courses-marks-edit'),

    path('courses/<slug:the_slug>/marks/final/set/<int:pk>/', views.set_final_course_mark_view, name='set-final-mark'),
    path('courses/<slug:the_slug>/marks/final/edit/<int:pk>/', views.edit_final_course_mark_view,
         name='edit-final-mark'),

    path('courses/lecture/<int:pk>/detail/', views.LectureDetailView.as_view(), name='lectures-detail'),
    path('courses/lecture/<int:pk>/edit/', views.LectureEditView.as_view(), name='lectures-edit'),
    path('courses/lecture/<int:pk>/file/add/', views.lecture_add_file, name='lectures-file-add'),
    path('courses/lecture/<int:pk>/file/delete/<int:num>', views.delete_lecture_file, name='lectures-file-delete'),
    path('courses/<slug:the_slug>/lecture/create/', views.LectureCreateView.as_view(), name='lectures-create'),

    path('courses/laboratory/<int:pk>/', views.LaboratoryDetailView.as_view(), name='laboratory-detail'),
    path('courses/laboratory/<int:pk>/edit/', views.LaboratoryEditView.as_view(), name='laboratory-edit'),
    path('courses/<slug:the_slug>/laboratory/create/', views.LaboratoryCreateView.as_view(), name='laboratory-create'),
    path('courses/laboratory/<int:pk>/file/add/', views.laboratory_add_file, name='laboratory-file-add'),
    path('courses/laboratory/<int:pk>/file/delete/<int:num>/', views.delete_laboratory_file,
         name='laboratory-file-delete'),

    path('courses/laboratory/<int:pk>/assignments/add/', views.AssignmentCreateView.as_view(),
         name='assignments-create'),
    path('courses/laboratory/<int:pk>/assignments/delete/<int:num>/', views.delete_assignment_view,
         name='assignments-delete'),


    path('courses/<slug:the_slug>/groups/', views.CourseGroupJoinListView.as_view(), name='group'),
    path('courses/<slug:the_slug>/groups/create/', views.course_group_create_view, name='group-create'),
    path('courses/<slug:the_slug>/groups/join/<int:num>', views.course_group_join_view, name='group-join-group'),
    path('courses/groups/<int:pk>/', views.CourseGroupEditView.as_view(), name='group-edit'),
    path('courses/<slug:the_slug>/groups/<int:num>/delete/', views.course_group_delete_view, name='group-delete'),

    path('courses/<slug:the_slug>/notices/', views.CourseNoticeView.as_view(), name='notices'),

    path('', include(router.urls)),
    path('api/list/courses/', CourseListView.as_view()),
    path('api/courses/<slug:the_slug>/additional-student/', additional_course_student),
]

app/support/urls.py
from django.urls import path

from support import views

app_name = 'support'

urlpatterns = [
    path('contact/', views.TicketCreateView.as_view(), name='support-contact'),
]

app/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('assignments/', views.AssignmentsView.as_view(), name='assignments'),
    path('schedule/', views.ScheduleView.as_view(), name='schedule'),
    path('notices/', views.NoticeView.as_view(), name='notices'),
    path('marks/', views.MarksView.as_view(), name='marks'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('profile/<int:pk>/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile-edit'),
    path('profile/img/delete/', views.delete_profile_image, name='profile-img-delete'),
]

app/courses/forms.py
from django import forms

from courses import models

tailwind_form = 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4' \
                 ' mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500'


class LectureCreateForm(forms.Form):
    """
    LectureCreateForm is used to create new Lecture at `courses.views.LectureCreateView`.
    """
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': tailwind_form,
        'placeholder': 'Tytuł',
    }))
    date = forms.DateField(widget=forms.DateInput(attrs={
        'class': tailwind_form,
        'placeholder': '01.01.2021'
    }))
    time = forms.TimeField(widget=forms.TimeInput(attrs={
        'class': tailwind_form,
        'placeholder': '12:30'
    }))
    duration = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': tailwind_form,
        'placeholder': '90',
        'min': '1'
    }))
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'class': tailwind_form,
        'cols': 30,
        'rows': 5
    }))
    show = forms.BooleanField(required=False)
    meeting = forms.BooleanField(initial=True, required=False)


class LaboratoryCreateForm(LectureCreateForm):
    """
    LaboratoryCreateForm is used to create new Laboratory at `courses.views.LaboratoryCreateView`.
    """
    group = forms.ModelChoiceField(queryset=models.CourseGroup.objects.all(),
                                   widget=forms.RadioSelect(attrs={'class': 'text-sm text-gray-700'}))


class CourseFileForm(forms.Form):
    """
    CourseFileForm is used to create/edit file within `course` module.
    """
    filename = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': tailwind_form,
        'placeholder': 'Nazwa pliku',
    }))
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'class': tailwind_form,
        'cols': 30,
        'rows': 5
    }))
    file = forms.FileField(required=True, widget=forms.FileInput(attrs={
        'class': tailwind_form
    }))


class CourseGroupModelForm(forms.ModelForm):
    """
    CourseGroupModelForm is used to create/edit `courses.CourseGroup` objects
    """
    class Meta:
        model = models.CourseGroup
        fields = ('name', 'students',)
        widgets = {
            'name': forms.TextInput(attrs={'class': tailwind_form}),
            'students': forms.CheckboxSelectMultiple(attrs={'class': 'text-sm text-gray-700'})
        }


class CourseNoticeModelForm(forms.ModelForm):
    """
    CourseNoticeModelForm is used to create/edit `courses.CourseNotice` objects
    """
    class Meta:
        model = models.CourseNotice
        fields = ('title', 'content',)
        widgets = {
            'title': forms.TextInput(attrs={'class': tailwind_form}),
            'content': forms.Textarea(attrs={
                'class': tailwind_form,
                'cols': 30,
                'rows': 5
            })
        }


class CourseMarkModelForm(forms.ModelForm):
    """
    CourseMarkModelForm is used to create/edit `courses.CourseMark` objects
    """
    class Meta:
        model = models.CourseMark
        fields = ('mark', 'description')
        widgets = {
            'mark': forms.NumberInput(attrs={'class': tailwind_form}),
            'description': forms.Textarea(attrs={
                'class': tailwind_form,
                'cols': 30,
                'rows': 5,
                'placeholder': 'Opis'
            }),
        }


class CourseSetFinalMarkModelForm(forms.ModelForm):
    """
    CourseSetFinalMarkModelForm is used to create/edit `courses.FinalCourseMark` objects
    """
    class Meta:
        model = models.FinalCourseMark
        fields = ('mark', 'description')
        widgets = {
            'mark': forms.NumberInput(attrs={'class': tailwind_form}),
            'description': forms.Textarea(attrs={
                'class': tailwind_form,
                'cols': 30,
                'rows': 5,
                'placeholder': 'Opis'
            }),
        }


class AssignmentCreateModelForm(forms.ModelForm):
    """
    AssignmentCreateModelForm is used to create/edit `courses.Assignment` objects
    """
    class Meta:
        model = models.Assignment
        fields = ('deadline', 'title', 'content')
        widgets = {
            'deadline': forms.DateTimeInput(attrs={
                'class': tailwind_form,
                'placeholder': '01.01.2021'
            }),
            'title': forms.TextInput(attrs={'class': tailwind_form, 'placeholder': 'Tytul'}),
            'content': forms.Textarea(attrs={
                'class': tailwind_form,
                'cols': 30,
                'rows': 5
            })
        }

app/courses/api/views.py
from rest_framework import generics, mixins, viewsets
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from courses import models
from users import models as users_models

from .permissions import IsTeacherOrReadOnly
from .serializers import CourseAdditionalStudentsSerializer, CourseSerializer


class CourseListView(mixins.ListModelMixin, generics.GenericAPIView):
    queryset = models.Course.objects.all()
    serializer_class = CourseSerializer
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def get_queryset(self):
        user = self.request.user
        qs = models.Course.objects.all()
        if user.is_teacher:
            teacher = users_models.Teacher.objects.get(pk=user.pk)
            qs = qs.filter(teachers__in=[teacher.pk])
        if user.is_student:
            student = users_models.Student.objects.get(pk=user.pk)
            qs = qs.filter(grade__students__in=[student.pk])

        name = self.request.query_params.get('name')
        teacher = self.request.query_params.get('teacher')
        has_exam = int(self.request.query_params.get('exam', 0))
        language = self.request.query_params.get('language')
        actual = self.request.query_params.get('actual')

        if name:
            qs = qs.filter(name__icontains=name)
        if teacher:
            qs = qs.filter(teachers__last_name__icontains=teacher)
        if has_exam and has_exam > 0:
            if has_exam == 1:
                qs = qs.filter(has_exam=True)
            if has_exam == 2:
                qs = qs.filter(has_exam=False)
        if language:
            qs = qs.filter(language=language.upper())
        if actual and actual == 'true':
            qs = [q for q in qs if q.is_actual]
        return qs


class CourseViewSet(mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    queryset = models.Course.objects.all()
    serializer_class = CourseAdditionalStudentsSerializer
    permission_classes = [IsTeacherOrReadOnly, IsAuthenticated]
    lookup_field = "slug"

    def get_queryset(self):
        user = self.request.user
        teacher = users_models.Teacher.objects.get(pk=user.pk)
        return teacher.courses_teaching.all()


@api_view(['POST'])
def additional_course_student(request, the_slug):
    if not request.user.is_authenticated or request.user.role != 'teacher':
        return Response(status=401)
    if request.method == 'POST':
        email = request.data.get('email')
        course = models.Course.objects.get(slug=the_slug)
        if email and course:
            try:
                student = users_models.Student.objects.get(email=email)
                if student in course.grade.students.all() or student in course.additional_students.all():
                    return Response(status=200, data={'message': 'Ten użytkownik jest już dodany.'})
                if student:
                    course.additional_students.add(student)
            except Exception:
                return Response(status=404)
            return Response(status=200, data={'message': 'Pomyślnie dodano uzytkownika do kursu.'})
        return Response(status=400)
    return Response(status=401)

app/templates/courses/courses-detail.html
{% extends "dashboard/dashboard.html" %}
{% load static %}

{% block title %}Szczegóły kursu{% endblock title %}


{% block dashboard_content %}
  <div class="font-sans leading-tight bg-grey-lighter p-4 md:pt-8">
    <div class="max-w-full mx-auto bg-white rounded-lg overflow-hidden shadow-lg">
      <div class="px-4 py-4 border-b-2 border-gray-200 mx-2">
        <h4 class="text-lg leading-6 font-medium text-gray-900 mb-2"><a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses' %}">Kursy</a> / {{ course.name }}</a></h4>
        <p class="text-sm text-gray-600"><span class="text-bold">Główny prowadzący: </span>
          <a href="{% url 'users:profile-detail' course.head_teacher.pk %}" class="text-blue-500 hover:text-blue-400">
            {{ course.head_teacher.first_name }} {{ course.head_teacher.last_name }}
          </a>
        </p>
        <p class="mt-1 text-sm text-gray-600"><span class="text-bold">Prowadzący: </span>
          {% for teacher in course.teachers.all %}
            <a href="{% url 'users:profile-detail' teacher.pk %}" class="text-blue-500 hover:text-blue-400">
              {{ teacher.first_name }} {{ teacher.last_name }}{% if not forloop.last %}, {% endif %}
            </a>
          {% endfor %}
        </p>
        <div class="text-sm text-gray-600">
          <p class="font-bold">Opis kursu:</p>
          <p>{% if course.description %}{{ course.description }}{% else %}-{% endif %}</p>
        </div>
        <div class="flex mt-4 mb-4">
          <a href="{% url 'courses:notices' course.slug %}" class="text-sm font-bold px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300 mr-2">
            Ogłoszenia
          </a>
          {% if request.user.is_student %}
            <a href="{% url 'courses:my-marks' course.slug %}" class="text-sm font-bold px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300 mr-2">
              Moje oceny
            </a>
          {% endif %}
          {% if request.user.email in student_without_groups_emails %}
          <a href="{% url 'courses:group' course.slug %}" class="text-sm font-bold px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300 mr-2">
            Dołącz do grupy
          </a>
          {% endif %}
          {% if request.user.is_teacher %}
            <a href="{% url 'courses:courses-edit' course.slug %}" class="text-sm font-bold px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
              Edytuj kurs
            </a>
            <a href="{% url 'courses:group' course.slug %}" class="ml-2 text-sm font-bold px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
              Zarządzaj grupami
            </a>
            <a href="{% url 'courses:courses-total-marks' course.slug %}" class="ml-2 text-sm font-bold px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
              Oceny
            </a>
          {% endif %}
        </div>
      </div>
      <div class="px-4 py-4 mx-2">
        <h4 class="text-lg leading-6 font-medium text-gray-900 mb-2">Dostępne wykłady</a></h4>
        {% if not available_lectures %}
        <p class="text-gray-700 text-sm">
          Nie znaleziono żadnego dostępnego wykładu.
        </p>
        {% endif %}
        {% for lecture in available_lectures %}
          <div class="flex mb-4">
            <div class="flex-shrink-0">
              <div class="flex flex-col items-center justify-center h-12 w-12 rounded-md {% if lecture.was_held %}bg-blue-400{% else %}bg-green-400{% endif %} text-white">
                {{ forloop.counter }}
              </div>
            </div>
            <div class="ml-4">
              <h4 class="text-lg leading-6 font-medium text-gray-900 transition-all duration-200 hover:text-gray-600">
                <a style="cursor: pointer;" href="{% url 'courses:lectures-detail' lecture.pk %}">{{ lecture.title }}</a>
              </h4>
              <p class="text-sm text-gray-600"><span class="font-medium">Data wydarzenia: </span>
                {{ lecture.date|date:"d.m.Y (H:i)" }}{% if lecture.was_held %}X{% endif %}
              </p>
              <p class="text-sm text-gray-600"><span class="font-medium">Szczegóły: </span>
                {{ lecture.description }}
              </p>
              <p class="text-sm text-gray-600"><span class="text-bold">Dodatkowe materiały: </span>
                {% if lecture.files.all %}
                  {% for file in lecture.files.all %}
                    <a class="text-blue-400 hover:text-blue-500" href="{{ file.file.url }}">{{ file.name }}</a>{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                {% else %}
                  -
                {% endif %}
              </p>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="px-4 py-4 mx-2">
        <h4 class="text-lg leading-6 font-medium text-gray-900 mb-2">Dostępne laboratoria</a></h4>
        {% if not available_labs %}
          <p class="text-gray-700 text-sm">
            Nie znaleziono żadnego dostępnego wykładu.
          </p>
        {% endif %}
        {% for lab in available_labs %}
          <div class="flex mb-4">
            <div class="flex-shrink-0">
              <div class="flex flex-col items-center justify-center h-12 w-12 rounded-md {% if lab.was_held %}bg-blue-400{% else %}bg-green-400{% endif %} text-white">
                {{ forloop.counter }}
              </div>
            </div>
            <div class="ml-4">
              <h4 class="text-lg leading-6 font-medium text-gray-900 transition-all duration-200 hover:text-gray-600">
                <a style="cursor: pointer;" href="{% url 'courses:laboratory-detail' lab.pk %}">{{ lab.title }}</a>
              </h4>
              <p class="text-sm text-gray-600"><span class="font-medium">Data wydarzenia: </span>
                {{ lab.date|date:"d.m.Y (H:i)" }}{% if lab.was_held %}X{% endif %}
              </p>
              <p class="text-sm text-gray-600"><span class="font-medium">Szczegóły: </span>
                {{ lab.description }}
              </p>
              <p class="text-sm text-gray-600"><span class="text-bold">Dodatkowe materiały: </span>
                {% if lab.files.all %}
                  {% for file in lab.files.all %}
                    <a class="text-blue-400 hover:text-blue-500" href="{{ file.file.url }}">{{ file.name }}</a>{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                {% else %}
                  -
                {% endif %}
              </p>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock dashboard_content %}

{% block extraheads %}
  {{ block.super }}
  <style type="text/css">
  .course__details {
    max-height: 0;
    transition: max-height 0.5s ease-in-out;
    overflow: hidden;
  }
  .course__details--active {
    max-height: 100%;
  }
  .indicator-active {
    transform: rotate(180deg);
  }
  </style>
{% endblock extraheads %}

app/templates/courses/courses-group-join.html
{% extends "dashboard/dashboard.html" %}
{% load static %}

{% block title %}Grupy{% endblock title %}


{% block dashboard_content %}
  <div id="groups" class="font-sans leading-tight bg-grey-lighter p-4 md:pt-8">
    <div class="max-w-full mx-auto bg-white rounded-lg overflow-hidden shadow-lg">
      <div class="px-4 py-4 border-b-2 border-gray-200 mx-2">
        <h4 class="text-lg leading-6 font-medium text-gray-900 mb-2">
          <a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses' %}">Kursy</a> /
          <a class="text-gray-700 transition-all duration-200 hover:text-gray-600" href="{% url 'courses:courses-detail' course.slug %}">{{ course.name }}</a> /
          Dołącz do grupy
        </h4>
        <div class="px-4 py-4 mx-2">
          <h4 class="text-lg leading-6 font-medium text-gray-900 mb-2">Dostępne grupy laboratoryjne</a></h4>
          {% if not groups %}
            <p class="text-gray-700 text-sm">
              Nie znaleziono żadnej grupy laboratoryjnej.
            </p>
          {% endif %}
          {% for group in groups %}
            <div class="flex mb-4">
              <div class="flex-shrink-0">
                <div class="flex flex-col items-center justify-center h-12 w-12 rounded-md bg-blue-400 text-white">
                  {{ forloop.counter }}
                </div>
              </div>
              <div class="ml-4">
                <h4 class="text-lg leading-6 font-medium text-gray-900 transition-all duration-200">
                  {{ group.name }}
                </h4>
                <p class="text-xs">Ilość studentów: {{ group.students_count }}</p>
                <div class="mt-2">
                  {% if request.user.is_student %}
                  <span @click="joinGroup({{ forloop.counter0 }})" class="cursor-pointer text-xs font-bold px-1 transition-all duration-200 py-1 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
                    Dołącz
                  </span>
                  {% else %}
                    <a href="{% url 'courses:group-edit' group.pk %}" class="cursor-pointer text-xs font-bold px-1 transition-all duration-200 py-1 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
                      Edytuj
                    </a>
                    <span @click="deleteGroup({{ forloop.counter0 }})" class="ml-2 cursor-pointer text-xs font-bold px-1 transition-all duration-200 py-1 px-2 rounded-lg bg-red-200 text-gray-800 hover:text-gray-900 hover:bg-red-300">
                      USUN
                    </span>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
        {% if request.user.is_teacher %}
          <a href="{% url 'courses:group-create' course.slug %}" class="text-sm font-bold mt-2 mb-4 px-4 transition-all duration-200 py-2 px-2 rounded-lg bg-gray-200 text-gray-800 hover:text-gray-900 hover:bg-gray-300">
            Dodaj grupę
          </a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock dashboard_content %}

{% block extraheads %}
  {{ block.super }}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
{% endblock extraheads %}

{% block extravue %}
  <script type="text/javascript">
    var app = new Vue({
      delimiters: ['[[', ']]'],
      el: '#groups',
      data: {},
      methods: {
        joinGroup: function(num) {
          Swal.fire({
            text: "Czy na pewno chcesz dołączyć do tej grupy?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Tak!',
          }).then((result) => {
            if (result.isConfirmed) {
              const slug = "{{ course.slug }}"
              window.location.href = `/courses/${slug}/groups/join/${num}`
            }
          })
        },
        deleteGroup: function (num) {
          Swal.fire({
            text: "Czy na pewno chcesz usunąć tę grupę?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Tak!',
          }).then((result) => {
            if (result.isConfirmed) {
              const slug = "{{ course.slug }}"
              window.location.href = `/courses/${slug}/groups/${num}/delete/`
            }
          })
        }
      }
    });
  </script>
{% endblock extravue %}